### ISSUE TITLE
mysql specific sql

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#1]
<=> is a mysql specific operator. Moodle supports postgres, ms sql and oracle and sql should be compatible with all database types:
eg:
https://github.com/blackbean/moodle-local_bbliveusers/blob/master/lib/bbliveusers.php#L60

**Comment by danmarsden** [comment]
"REPLACE INTO" is also mysql specific:
https://github.com/blackbean/moodle-local_bbliveusers/blob/master/lib/bbliveusers.php#L194

**Comment by danmarsden** [comment]
these look like they will fail in other db types too:
https://github.com/blackbean/moodle-local_bbliveusers/blob/master/lib/bbliveusers.php#L194
https://github.com/blackbean/moodle-local_bbliveusers/blob/master/lib/bbliveusers.php#L344

looks like some missing fields in the group by statement.

**Comment by brunomagalhaes** [comment]
Hi Dan,

First of all, thank you for help, it's very much appreciated!!!

We just fixed the <=> operator and order by issues. The REPLACE INTO "issue" is more of an optimization than an issue, the alternative would be to query the database more more time and execute the appropriate command accordingly. But we've optimized those runtimes as much as we could.

Best,
Bruno

**Comment by brunomagalhaes** [comment]
Removed the "REPLACE INTO" query by using a check-if-exists query before trying to store the user's live timestamp within the database.
