### ISSUE TITLE
php warnings on install.

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#10]
Notice: Use of undefined constant CAP_DENY - assumed 'CAP_DENY' in /home/dan/www/moodle/local/bbliveusers/db/access.php on line 32

Notice: Use of undefined constant CAP_DENY - assumed 'CAP_DENY' in /home/dan/www/moodle/local/bbliveusers/db/access.php on line 34

Notice: Use of undefined constant CAP_DENY - assumed 'CAP_DENY' in /home/dan/www/moodle/local/bbliveusers/db/access.php on line 35

Notice: Use of undefined constant CAP_DENY - assumed 'CAP_DENY' in /home/dan/www/moodle/local/bbliveusers/db/access.php on line 42

Notice: Use of undefined constant CAP_DENY - assumed 'CAP_DENY' in /home/dan/www/moodle/local/bbliveusers/db/access.php on line 44

Notice: Use of undefined constant CAP_DENY - assumed 'CAP_DENY' in /home/dan/www/moodle/local/bbliveusers/db/access.php on line 45

**Comment by brunomagalhaes** [comment]
Fixed.
