### ISSUE TITLE
missing strings on install

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#11]
This is because I installed the local_bbliveusers block by itself while testing - there are 2 options to fix this.

1) move the strings to the local plugin.
2) add a dependency on the blcok in version.php to state that the block must be installed at the same time as the local plugin.

Invalid get_string() identifier: 'title_settings' or component 'block_bbliveusers'. Perhaps you are missing $string['title_settings'] = ''; in /lang/en/block_bbliveusers.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 7124 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 34 of /local/bbliveusers/settings.php: call to get_string()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 7997 of /lib/adminlib.php: call to require()
line 7884 of /lib/adminlib.php: call to admin_get_root()
line 19 of /admin/upgradesettings.php: call to admin_externalpage_setup()
Invalid get_string() identifier: 'label_timeout' or component 'block_bbliveusers'. Perhaps you are missing $string['label_timeout'] = ''; in /lang/en/block_bbliveusers.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 7124 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 41 of /local/bbliveusers/settings.php: call to get_string()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 7997 of /lib/adminlib.php: call to require()
line 7884 of /lib/adminlib.php: call to admin_get_root()
line 19 of /admin/upgradesettings.php: call to admin_externalpage_setup()
Invalid get_string() identifier: 'help_timeout' or component 'block_bbliveusers'. Perhaps you are missing $string['help_timeout'] = ''; in /lang/en/block_bbliveusers.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 7124 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 43 of /local/bbliveusers/settings.php: call to get_string()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 7997 of /lib/adminlib.php: call to require()
line 7884 of /lib/adminlib.php: call to admin_get_root()
line 19 of /admin/upgradesettings.php: call to admin_externalpage_setup()
Invalid get_string() identifier: 'title_settings' or component 'block_bbliveusers'. Perhaps you are missing $string['title_settings'] = ''; in /lang/en/block_bbliveusers.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 7124 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 34 of /local/bbliveusers/settings.php: call to get_string()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 7997 of /lib/adminlib.php: call to require()
line 22 of /admin/upgradesettings.php: call to admin_get_root()
Invalid get_string() identifier: 'label_timeout' or component 'block_bbliveusers'. Perhaps you are missing $string['label_timeout'] = ''; in /lang/en/block_bbliveusers.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 7124 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 41 of /local/bbliveusers/settings.php: call to get_string()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 7997 of /lib/adminlib.php: call to require()
line 22 of /admin/upgradesettings.php: call to admin_get_root()
Invalid get_string() identifier: 'help_timeout' or component 'block_bbliveusers'. Perhaps you are missing $string['help_timeout'] = ''; in /lang/en/block_bbliveusers.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 7124 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 43 of /local/bbliveusers/settings.php: call to get_string()
line 67 of /lib/classes/plugininfo/local.php: call to include()
line 642 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
line 7997 of /lib/adminlib.php: call to require()
line 22 of /admin/upgradesettings.php: call to admin_get_root()
Skip to main content

**Comment by brunomagalhaes** [comment]
Done.

**Comment by danmarsden** [comment]
I can't see a code change that fixes this yet? - or is it still incoming?

**Comment by brunomagalhaes** [comment]
HI Dan,

The missing string was related to the block plugin not the local plugin. Here Is the related code fix:

https://github.com/blackbean/moodle-block_bbliveusers/commit/c339ebf1fca609f46c3a6afcffcc0b3f5a9f300d

Best,
Bruno

**Comment by danmarsden** [comment]
No. Your local plugin uses strings from your block plugin. But you can install the local plugin by itself. You need to stop using block strings in the local plugin or add a dependency in version.php that requires the block plugin to be installed when the local plugin is installed. Make sense?

**Comment by brunomagalhaes** [comment]
Oh, I see now, my bad.

Fixed within the following commit:

https://github.com/blackbean/moodle-local_bbliveusers/commit/dbd93e9f9e477ca6ec93a0631706de1a9202ad52

Best,
Bruno

**Comment by danmarsden** [comment]
yep - that was it! :-)
