### ISSUE TITLE
fetch.php fails in postgres

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#12]
the fetch.php file throws a db error on a postgres db.

One of the best things about travis integration is that you can run unit and behat tests against both Postgres and Mysql - If you wrote a simple unit test or behat test that verified the results from your fetch.php/group.php/ping.php etc files then you could rely on travis to tell you when a change to your sql has caused a problem.

**Comment by brunomagalhaes** [comment]
Fixed.... Technically speaking MySQL 5.4, or greater, should also have complained about missing SELECT column within GROUP BY, but that was not the case. Probably we are running SQL_MODE="" on our clients production servers. :\
