### ISSUE TITLE
consider adding travis ci support

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#4]
You may want to consider adding travis-ci support to your plugin here in github - this allows us to see how well your code complies with moodle coding guidelines - more information on this is available here:
https://moodle.org/mod/forum/discuss.php?d=323384

**Comment by danmarsden** [comment]
the moodle.org plugins db runs many of the same checks that the travis integration does - currently it is showing 1361 errors - the full report is also available here:
https://moodle.org/plugins/pluginversion.php?id=16441
(you will need to be logged into Moodle with the black bean account to view that report as this entry has not been approved yet)

**Comment by brunomagalhaes** [comment]
Done

**Comment by danmarsden** [comment]
Great! - will try to take another look at the updates later today.
