### ISSUE TITLE
Improvements to session handling

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#5]
Adding a new issue here so that you don't forget about this.

The session handling you've implmeneted looks better, although instead of re-using CFG->sessiontimeout it would probably be better to define your own setting in the plugin for a timeout. Using $CFG->sessiontimeout as your parameter basically doubles the sessiontimeout value for a site and doesn't give your users a lot of control over it.

If you added a new setting to your plugin to control this timeout you could add something like the following help text to that setting:

"This setting controls how long the plugin should make regular checks to the server to keep the user logged in. The user will not be logged out after this time, but will be logged out after this time has expired and the sessiontimeout value has expired on your site. For example if you have this set to 2 hours, and the sessiontimeout value set to 2 hours, the user will be logged out after 4 hours of inactivity."

That's just a quick draft - you may want to tidy it up/adjust it etc.

**Comment by brunomagalhaes** [comment]
Hi Dan,

Sorry the long delay, it's been crazy so over here with other projects and clients that we dropped the ball on this issue

But finally, we just pushed the new setting implementation based on your feedback.

Thank you so much for your help.
