### ISSUE TITLE
count.php can be used by any user

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#7]
is that correct? - should all users of the site be able to see how many users are logged in - or potentialy how many users are in the site by passing old timestamps?

should there be a capability check in this file?

**Comment by danmarsden** [comment]
fetch.php is the same - shouldn't there be a capability check in there?

**Comment by danmarsden** [comment]
...and group.php :-)

**Comment by brunomagalhaes** [comment]
Hi Dan,

Yes, it should have and now, thanks to you, it does. :)

By the way, you don't pass the raw timestamp, but the time offset. If you want the live data from last minute you pass limit=60, but if you want from the last hour you should pass limit=3600, and so forth.

Best,
Bruno
