### ISSUE TITLE
missing privacy api class

### ISSUE THREAD

**Issue by danmarsden** [blackbean/moodle-local_bbliveusers#8]
Moodle now implements a new privacy api - it would be nice if you could implement this in your plugin. Sites that use continuous integration processes will not be able to use your plugin as Moodle now includes unit tests to check that all installed plugins contain appropriate privacy classes.
more information on the privacy api is here:
https://docs.moodle.org/dev/Privacy_API

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by brunomagalhaes** [comment]
We were reading the Privacy API documentation... Can we remove the Privacy Provider for now and fully implement it on the next version?

**Comment by danmarsden** [comment]
Adding the privacy api is not currently a blocker for approval in the plugins db, but it will likely be a blocker for some people wanting to use your plugin. Feel free to re-submit the plugin for approval before completing the privacy api class.
